### ISSUE TITLE
Styling Registration Page

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandInHAndOut#27]
Rules must be displayed in a styled method rather than simple text

**Comment by AbdulSuboor-Syed** [comment]
Removing the image
Adding bootstrap cards which defines the rules of registration

- [ ] Card for Email requirement
- [ ] Card for Password requirment

**Comment by HemaSreeRathnamMachha** [comment]
Cards created for email and password in registration page
