### ISSUE TITLE
Testing Registration Page after adding User address information

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandInHAndOut#28]
- [x] User is able to register using the required email
- [x] User is able to register using the required password
- [x] User is able to enter Address
- [x] User is able to enter City
- [x] User is able to enter State
- [x] All the information is stored in the database

**Comment by AbdulSuboor-Syed** [comment]
Reminder: Update database before you start testing

**Comment by tata1141** [comment]
All the test cases are working.
