### ISSUE TITLE
Testing role based authentication

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandInHAndOut#32]
- [x] List roles page requires admin role
- [x] Create roles page requires admin role
- [x] Create page requires admin role
- [x] index page requires admin role

**Comment by HemaSreeRathnamMachha** [comment]
To be able to view create page admin role must be assigned to the user

**Comment by HimajaParachuri** [comment]
user must be assigned to create roles page which requires the admin role is tested.

**Comment by tata1141** [comment]
All the test cases are working successfully.
