### ISSUE TITLE
Testing Role based navigation items

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandInHAndOut#33]
- [x] List link is only accessible to Admin role
- [x] Create is only accessible to Admin role
- [x] List Roles is only accessible to Admin role

**Comment by HemaSreeRathnamMachha** [comment]
creation of a list of books available is only accessible to admin

**Comment by HimajaParachuri** [comment]
Create is only accessible to Admin role is tested and working.

**Comment by tata1141** [comment]
All the list roles is accessible to admin role only.
All the test cases are working.
